name: fresh_graphql
description: An graphql link for token refresh. Built on top of package:graphql and manages authentication tokens transparently.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh
funding: [https://github.com/sponsors/felangel]

version: 0.7.0

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  fresh: ^0.5.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  http: ^1.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.16.8
