name: fresh_graphql
description: An graphql link for token refresh. Built on top of package:graphql and manages authentication tokens transparently.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh

version: 0.5.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fresh: ^0.4.0
  gql_exec: ^1.0.0
  gql_link: ^1.0.0
  http: ^1.1.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.8
