name: fresh
description: An token refresh library for dart. This package exposes the core components that are common to various refresh token implementations (REST, GraphQL, etc...).
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh
funding: [https://github.com/sponsors/felangel]

version: 0.5.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.16.0
