name: jsonplaceholder_client
description: A jsonplaceholder client for Dart.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  fresh:
  fresh_dio:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

dependency_overrides:
  fresh:
    path: ../../../../fresh
  fresh_dio:
    path: ../../../