name: jsonplaceholder_client
description: A jsonplaceholder client for Dart.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  fresh_dio:
    path: ../../../
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.0
  very_good_analysis: ^2.4.0
