name: fresh_example
description: Fresh Http Client Example Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  jsonplaceholder_client:
    path: packages/jsonplaceholder_client
  photos_repository:
    path: packages/photos_repository
  user_repository:
    path: packages/user_repository
  very_good_analysis: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
