name: photos_repository
description: A Photos Dart Repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  jsonplaceholder_client:
    path: ../jsonplaceholder_client
  very_good_analysis: ^2.4.0
