name: fresh_dio
description: An http interceptor for token refresh. Fresh is built on top of package:dio and manages authentication tokens transparently.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh

version: 0.3.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  fresh: ^0.4.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.16.0
  very_good_analysis: ^2.4.0
