name: fresh_dio
description: An http interceptor for token refresh. Fresh is built on top of package:dio and manages authentication tokens transparently.
repository: https://github.com/felangel/fresh
issue_tracker: https://github.com/felangel/fresh/issues
homepage: https://github.com/felangel/fresh
funding: [https://github.com/sponsors/felangel]

version: 0.5.1

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  fresh: ^0.5.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.16.0
