name: fresh_dio

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/fresh_dio.yaml"
      - "packages/fresh_dio/pubspec.yaml"
      - "packages/fresh_dio/lib/**"
      - "packages/fresh_dio/test/**"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/fresh_dio.yaml"
      - "packages/fresh_dio/pubspec.yaml"
      - "packages/fresh_dio/lib/**"
      - "packages/fresh_dio/test/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/fresh_dio
