name: publish/fresh_graphql

on:
  push:
    tags:
      - "fresh_graphql-v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    environment: pub.dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC

    steps:
      - name: ðŸ“š Git Checkout
        uses: actions/checkout@v6

      - name: ðŸ“¦ Publish
        uses: ./.github/actions/pub_publish
        with:
          working_directory: packages/fresh_graphql
